### PR TITLE
Upgrade butler server dependencies

### PR DESCRIPTION
**Pull request by dhirving**
## Checklist

- [ ] ran Jenkins
- [ ] added a release note for user-visible changes to `doc/changes`
- [ ] (if changing dimensions.yaml) make a copy of dimensions.yaml in `configs/old_dimensions`

### CODE REVIEW

**Comment by dhirving** [comment]
This needs a new release of `lsst-sphgeom` for the tests to pass.  A PyPI upload has not occurred for that package since weekly 44.  There is a PR open to fix it (DM-48232).

**Comment by andy-slac** [comment]
> This needs a new release of `lsst-sphgeom` for the tests to pass.

Matthias promises a fix later today.

**Comment by andy-slac** [comment]
@dhirving, `sphgeom` is updated on PyPI. I can merge my ticket without updating dependencies if you plan to merge this branch ~soon?

**Comment by dhirving** [comment]
@andy-slac Go ahead and merge, I'll follow you with this one.

**Pull request merged**
