### PR TITLE
DM-33417: manual back port of DM-33360 — Improve performance of https as_local() method

### PR DESCRIPTION
**Pull request by airnandez**
## Checklist

- [x] ran Jenkins: done on macOS, ongoing on centOS
- [ ] added a release note for user-visible changes to `doc/changes` (n/a)

### CODE REVIEW

**Comment by timj** [comment]
I think you will need to cherry pick 9afaeb3e  to fix the mypy problem.

Can you also add in that as_local test that was included in the original PR? That can go into tests/test_uri.py (at least one of the tests so that as_local can be shown to work). It will have to use a ButlerURI of course.

**Comment by timj** [comment]
The test failures are from moto3. You will have to pin the moto version to <3 in requirements.txt (or we backport DM-33347 -- which isn't needed because we pin moto in the rubin-env that is used for v23).

**Comment by timj** [comment]
Generally we don't want the branch name for the backport to differ from the original branch (so we want to reuse the same ticket) -- but I guess in this case it's probably okay because a completely different package is being modified.

**Comment by airnandez** [comment]
> cherry pick 9afaeb3 to fix the mypy problem.

✅

> add in that as_local test ... into tests/test_uri.py

✅

> pin the moto version to <3 in requirements.txt

✅

> Generally we don't want the branch name for the backport to differ from the original branch...

Understood. I thought that since this was a different PR it required a different JIRA issue and therefore a different branch name.

Thanks for your guidance!

**Comment by timj** [comment]
I merged it.  Yes, we add v23 to the ticket branch name for backports.

**Pull request merged**
