### PR TITLE
DM-33204: Add deprecation warning for ButlerURI

### PR DESCRIPTION
**Pull request by timj**
The code is a bit hairy...

@TallJimbo let me know if you have any better ideas, especially regarding the subclasses trying to instantiate something.

## Checklist

- [x] ran Jenkins
- [ ] added a release note for user-visible changes to `doc/changes`

### CODE REVIEW

**Review by TallJimbo — APPROVED** [review]
I don't really have an opinion about whether this is better or worse than no deprecation warning at all, but I don't have any better ideas.  I spent a few minutes researching import hooks in the hopes of finding a way to emit a warning when the symbol is imported or accessed as an attribute of a module, but came up empty-handed.

**Comment by timj** [comment]
There can't possibly be many ButlerURI users out in the wild so this should be fine even if it's a bit convoluted.

**Comment by timj** [comment]
Looks like I can't merge this until `pipe_base` loses `ButlerURI` -- mostly because one of the tests in `pipelines_check` is getting confused by the warnings come out of `pipe_base` (although I'll take a quick look at the test and see if it's a real problem).

**Comment by TallJimbo** [comment]
`pipe_base` changes are pretty thoroughly backed up behind other changes now.  If you want to move faster feel free to convert it (by cherry-picking b014171b73c1271bfc3db8df568fcff7fa6d8931 or otherwise) and I'll rebase.

**Comment by timj** [comment]
I'll take a quick look at that.

**Pull request merged**
