### PR TITLE
DM-44362: Fix unit test for spatial overlaps

### PR DESCRIPTION
**Pull request by andy-slac**
Using non-common skypix is going to be deprecated in favor of a
direct use of regions. New query system raises NotImplementedError
for non-common skypix, this patch replaces that exception with
a new exception class to support exception propagation from remote
butler to client.

`test_skypix_constraint_queries` unit test is updated to handle
exceptions from the new query system. When direct butler switches
to the new query system, that test can be removed or changed to
always expect the exceptions.

## Checklist

- [x] ran Jenkins
- [ ] added a release note for user-visible changes to `doc/changes`
- [ ] (if changing dimensions.yaml) make a copy of dimensions.yaml in `configs/old_dimensions`

### CODE REVIEW

**Comment by andy-slac** [comment]
@TallJimbo, I tried few different ideas and ended up with a special visitor that rewrites predicates which use non-common skypix. A complicated thing is that it also needs to override dimension group in the tree to replace skypix there too. It fixes that particular query that was broken in the unit test with `htm11` constraint, but that unit test is still failing on a subsequent query. Before I try to fix the next thing, could you check that this new visitor makes sense or maybe I need something different?

**Comment by TallJimbo** [comment]
We talked about this at the Tuesday standup (while you were on vacation), and given the new complexity that seems to be required, I think we should really consider deprecating this functionality instead, since I think the primary reason it's important in the old query system is as a workaround for general geometry overlap queries, and we can do that better in the new query system if we do it more directly.

**Comment by andy-slac** [comment]
I'm ok with deprecation, but does that mean that we still need to support until next release? Or is it fine if it's broken for remote butler only?

**Comment by TallJimbo** [comment]
I think it's fine for it to be broken for RemoteButler only for now; the deprecation period will constrain the timeline for having the DirectButler's old query methods delegate to the new system, but there are other differences we plan to deprecate in that category already.  Those are being tracked on DM-43587, and I've added this issue there as well.

**Review by TallJimbo — APPROVED** [review]

**Pull request merged**
