### PR TITLE
DM-43208: Expose Loader

### PR DESCRIPTION
**Pull request by arunkannawadi**
## Checklist

- [x] ran Jenkins
- [x] added a release note for user-visible changes to `doc/changes`

### CODE REVIEW

**Review by jchiang87 — APPROVED** [review]
Looks good!  Thanks so much!

**Comment by timj** [comment]
`Loader` is an internal helper class. Why do we need it to be public? If people really need it, it needs to have a better name.

**Comment by arunkannawadi** [comment]
If @jchiang87 needs it by the weekly that gets tagged tonight, I'll merge this and we can use a better name later. If not, I can wait on this.

**Comment by timj** [comment]
Why though? Is there some discussion on Slack? Is he reading his own YAML files and wants the include support? Can he read them using the Config class directly and then converting Config to a dict? This really is an internal routine that was not designed to be public.

**Pull request closed without merging**
