### PR TITLE
DM 47944: Fix calibration summary bug in v28

### PR DESCRIPTION
**Pull request by mwittgen**
## Checklist

- [x] ran Jenkins
- [ ] added a release note for user-visible changes to `doc/changes`
- [ ] (if changing dimensions.yaml) make a copy of dimensions.yaml in `configs/old_dimensions`

### CODE REVIEW

**Comment by timj** [comment]
I'm a bit confused with the failures because it's trying to merge into main:

```
 HEAD is now at cd8c3a50 Merge 6f8970208fc789e7b4bc8ae1ba903fde71f376af into f8303a5aea0268e78ae1e5ceb0ca15252ed2f26e
```

even though it says v28.0.x. -- the failure is consistent with main being involved.

**Comment by mwittgen** [comment]
That could be my fault, when I originally opened the PR it was set to main.

**Comment by mwittgen** [comment]
Let's see what close/reopen the PR does.

**Comment by mwittgen** [comment]
jenkins run: https://rubin-ci.slac.stanford.edu/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/3388/pipeline

**Comment by timj** [comment]
Aha. That fixed it.

**Review by TallJimbo — APPROVED** [review]

**Pull request merged**
